# Shell variables
# Generated by 'wal'
wallpaper='/home/emir/Pictures/wallpapers/haru.jpg'

# Special
background='#0f0b19'
foreground='#bf8c9b'
cursor='#bf8c9b'

# Colors
color0='#0f0b19'
color1='#17494D'
color2='#24555A'
color3='#245B62'
color4='#5C5C43'
color5='#A94B39'
color6='#A65234'
color7='#bf8c9b'
color8='#85626c'
color9='#17494D'
color10='#24555A'
color11='#245B62'
color12='#5C5C43'
color13='#A94B39'
color14='#A65234'
color15='#bf8c9b'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
